dist: xenial
language: python
python:
  - 3.6
  - 3.7
install:
  - pip install -e .
  - pip install pytest pytest-cov codecov pytest-mock snapshottest
script:
  - pytest --cov
after_success:
  - codecov
matrix:
  include:
    - python: 3.7
      script:
        - pip install black mypy pylint
        - pylint ariadne tests setup.py
        - mypy ariadne --ignore-missing-imports
        - black --check .