language: python
python:
  - 3.5
  - 3.6
install:
  - python setup.py install
  - pip install pytest pytest-cov codecov
script:
  - pytest --cov
after_success:
  - codecov
matrix:
  include:
    - python: 3.6
      script:
        - pip install black mypy pylint
        - pylint ariadne tests
        - mypy ariadne --ignore-missing-imports
        - black --check ariadne tests