language: python
python:
  - 3.5
  - 3.6
  - 3.7
install:
  - python setup.py install
  - pip install mypy pylint pytest pytest-cov
  - pip install codecov
script:
  - pytest --cov
  - pylint ariadne tests
  - mypy prices --ignore-missing-imports
after_success:
  - codecov